port: 7890
allow-lan: true
mode: Rule

dns:
  enable: true
  listen: ""
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 127.0.0.1
    - 223.5.5.5
    - 1.0.0.1

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

  nameserver-policy:
    'www.baidu.com': '114.114.114.114'
